### ISSUE TITLE
Error in with saving NORKYST data

### ISSUE THREAD

**Issue by gauteh** [MET-OM/metocean-api#22]
```
from metocean_api import ts
df_ts = ts.TimeSeries(lon=1.320, lat=53.324,
                   start_time='2012-01-01', end_time='2024-09-30' ,
                   product='NORKYST800')
print(df_ts)
df_ts.import_data(save_csv=True, save_nc=True)
```

```
<metocean_api.ts.ts_mod.TimeSeries object at 0x7aedf6adaab0>
Directory  cache  Created
Traceback (most recent call last):
  File "/home/gauteh/met/misc/sandviken/mo-sandv.py", line 6, in <module>
    df_ts.import_data(save_csv=True, save_nc=True)
  File "/home/gauteh/.mconda3/envs/metocean-stats/lib/python3.12/site-packages/metocean_api/ts/ts_mod.py", line 110, in import_data
    self.data = NORKYST800_ts(self, save_csv = save_csv,save_nc = save_nc)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gauteh/.mconda3/envs/metocean-stats/lib/python3.12/site-packages/metocean_api/ts/read_metno.py", line 239, in NORKYST800_ts
    x_coor_str, y_coor_str, infile = get_url_info(product=self.product, date=date_list[i])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gauteh/.mconda3/envs/metocean-stats/lib/python3.12/site-packages/metocean_api/ts/aux_funcs.py", line 133, in get_url_info
    print(infile)
          ^^^^^^
UnboundLocalError: cannot access local variable 'infile' where it is not associated with a value

```

**Comment by KonstantinChri** [comment]
This problem is related to the availability of NORKYST800 data (after 9.2016)

**Comment by gauteh** [comment]
Ok, I is that when they start? I thought it was 2012.

**Comment by KonstantinChri** [comment]
01.2017-09.2024
